
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ucelik
 */
public class TurEngSozluk extends javax.swing.JFrame {

  /**
   * Creates new form TurEngSozluk
   */
  public TurEngSozluk() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jTabbedPaneSOZLUK = new javax.swing.JTabbedPane();
    jPanelKAYDET = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextFieldTURKCE = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextFieldENGLISH = new javax.swing.JTextField();
    jButtonKAYDET = new javax.swing.JButton();
    jPanelLISTELE = new javax.swing.JPanel();
    jButtonLISTELE = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaLISTE = new javax.swing.JTextArea();
    jPanelLISTE = new javax.swing.JPanel();
    jButtonLISTE = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jListKELIMELER = new javax.swing.JList<>();
    jPanelARAMA = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jTextFieldARAMA = new javax.swing.JTextField();
    jRadioButtonTUMU = new javax.swing.JRadioButton();
    jRadioButtonICINDE = new javax.swing.JRadioButton();
    jButtonARAMA = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextAreaARAMA = new javax.swing.JTextArea();
    jPanelSILME = new javax.swing.JPanel();
    jButtonGUNCELLE = new javax.swing.JButton();
    jButtonSIL = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    jListSIL = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("TÜRKÇE");

    jTextFieldTURKCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel2.setText("ENGLISH");

    jTextFieldENGLISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jTextFieldENGLISH.setToolTipText("");

    jButtonKAYDET.setBackground(new java.awt.Color(255, 255, 153));
    jButtonKAYDET.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButtonKAYDET.setText("KAYDET");
    jButtonKAYDET.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonKAYDETActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelKAYDETLayout = new javax.swing.GroupLayout(jPanelKAYDET);
    jPanelKAYDET.setLayout(jPanelKAYDETLayout);
    jPanelKAYDETLayout.setHorizontalGroup(
      jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelKAYDETLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelKAYDETLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(29, 29, 29)
            .addComponent(jTextFieldTURKCE))
          .addGroup(jPanelKAYDETLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addGroup(jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextFieldENGLISH)
              .addGroup(jPanelKAYDETLayout.createSequentialGroup()
                .addComponent(jButtonKAYDET, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    jPanelKAYDETLayout.setVerticalGroup(
      jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelKAYDETLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTextFieldTURKCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(39, 39, 39)
        .addGroup(jPanelKAYDETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jTextFieldENGLISH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39)
        .addComponent(jButtonKAYDET)
        .addContainerGap(50, Short.MAX_VALUE))
    );

    jTabbedPaneSOZLUK.addTab("KAYDET", jPanelKAYDET);

    jButtonLISTELE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButtonLISTELE.setText("KELİMELERİ LİSTELE");
    jButtonLISTELE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLISTELEActionPerformed(evt);
      }
    });

    jTextAreaLISTE.setColumns(20);
    jTextAreaLISTE.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    jTextAreaLISTE.setRows(5);
    jScrollPane1.setViewportView(jTextAreaLISTE);

    javax.swing.GroupLayout jPanelLISTELELayout = new javax.swing.GroupLayout(jPanelLISTELE);
    jPanelLISTELE.setLayout(jPanelLISTELELayout);
    jPanelLISTELELayout.setHorizontalGroup(
      jPanelLISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelLISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonLISTELE, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
          .addComponent(jScrollPane1))
        .addContainerGap())
    );
    jPanelLISTELELayout.setVerticalGroup(
      jPanelLISTELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLISTELELayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonLISTELE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPaneSOZLUK.addTab("LİSTELEME", jPanelLISTELE);

    jButtonLISTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButtonLISTE.setText("LİSTELE");
    jButtonLISTE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLISTEActionPerformed(evt);
      }
    });

    jListKELIMELER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jScrollPane2.setViewportView(jListKELIMELER);

    javax.swing.GroupLayout jPanelLISTELayout = new javax.swing.GroupLayout(jPanelLISTE);
    jPanelLISTE.setLayout(jPanelLISTELayout);
    jPanelLISTELayout.setHorizontalGroup(
      jPanelLISTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLISTELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelLISTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonLISTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelLISTELayout.setVerticalGroup(
      jPanelLISTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLISTELayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonLISTE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPaneSOZLUK.addTab("LİSTE", jPanelLISTE);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel3.setText("Aranacak Kelime");

    jTextFieldARAMA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    buttonGroup1.add(jRadioButtonTUMU);
    jRadioButtonTUMU.setText("TÜMÜ");

    buttonGroup1.add(jRadioButtonICINDE);
    jRadioButtonICINDE.setText("İÇİNDE GEÇEN");

    jButtonARAMA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonARAMA.setText("KELİME ARA");
    jButtonARAMA.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonARAMAActionPerformed(evt);
      }
    });

    jTextAreaARAMA.setColumns(20);
    jTextAreaARAMA.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    jTextAreaARAMA.setRows(5);
    jScrollPane3.setViewportView(jTextAreaARAMA);

    javax.swing.GroupLayout jPanelARAMALayout = new javax.swing.GroupLayout(jPanelARAMA);
    jPanelARAMA.setLayout(jPanelARAMALayout);
    jPanelARAMALayout.setHorizontalGroup(
      jPanelARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelARAMALayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3)
          .addGroup(jPanelARAMALayout.createSequentialGroup()
            .addComponent(jRadioButtonTUMU)
            .addGap(18, 18, 18)
            .addComponent(jRadioButtonICINDE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButtonARAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
          .addGroup(jPanelARAMALayout.createSequentialGroup()
            .addComponent(jLabel3)
            .addGap(18, 18, 18)
            .addComponent(jTextFieldARAMA)))
        .addContainerGap())
    );
    jPanelARAMALayout.setVerticalGroup(
      jPanelARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelARAMALayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jTextFieldARAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanelARAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButtonTUMU)
          .addComponent(jRadioButtonICINDE)
          .addComponent(jButtonARAMA))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPaneSOZLUK.addTab("ARAMA", jPanelARAMA);

    jButtonGUNCELLE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButtonGUNCELLE.setText("GÜNCELLE");
    jButtonGUNCELLE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGUNCELLEActionPerformed(evt);
      }
    });

    jButtonSIL.setBackground(new java.awt.Color(255, 102, 102));
    jButtonSIL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jButtonSIL.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSIL.setText("!!! SİL !!!");
    jButtonSIL.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSILActionPerformed(evt);
      }
    });

    jListSIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jScrollPane4.setViewportView(jListSIL);

    javax.swing.GroupLayout jPanelSILMELayout = new javax.swing.GroupLayout(jPanelSILME);
    jPanelSILME.setLayout(jPanelSILMELayout);
    jPanelSILMELayout.setHorizontalGroup(
      jPanelSILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelSILMELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelSILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4)
          .addGroup(jPanelSILMELayout.createSequentialGroup()
            .addComponent(jButtonGUNCELLE, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jButtonSIL, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanelSILMELayout.setVerticalGroup(
      jPanelSILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelSILMELayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelSILMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonGUNCELLE)
          .addComponent(jButtonSIL))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPaneSOZLUK.addTab("SİLME", jPanelSILME);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPaneSOZLUK)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPaneSOZLUK)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonKAYDETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKAYDETActionPerformed
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    System.out.println("yol:" + adres);
    String tur = this.jTextFieldTURKCE.getText();
    String eng = this.jTextFieldENGLISH.getText();
    try {
      File dosya = new File(adres);
      FileWriter dosyaYazici = new FileWriter(dosya, true);
      BufferedWriter satirYazici = new BufferedWriter(dosyaYazici);
      satirYazici.write(tur + " = " + eng);
      satirYazici.newLine(); // alt satıra geçiş yapar
      satirYazici.close();
      JOptionPane.showMessageDialog(this, "Kayıt Başarılı");
      this.jTextFieldTURKCE.setText("");
      this.jTextFieldENGLISH.setText("");
    } catch(IOException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
  }//GEN-LAST:event_jButtonKAYDETActionPerformed

  private void jButtonLISTELEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLISTELEActionPerformed
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    String kelimeler = "";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        // her bir satırı okuyup kelimeler değişkenine aktarıyoruz
        kelimeler += okuyucu.nextLine() + "\n";
      }
      okuyucu.close();
      this.jTextAreaLISTE.setText(kelimeler);
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
  }//GEN-LAST:event_jButtonLISTELEActionPerformed

  DefaultListModel dlmLISTE = new DefaultListModel();
  private void jButtonLISTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLISTEActionPerformed
    dlmLISTE.clear();
    this.jListKELIMELER.setModel(dlmLISTE);
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        this.dlmLISTE.addElement(okuyucu.nextLine());
      }
      this.jListKELIMELER.setModel(dlmLISTE);
      okuyucu.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
  }//GEN-LAST:event_jButtonLISTEActionPerformed

  private void jButtonARAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonARAMAActionPerformed
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    String sonuc = "";
    String arananKelime = this.jTextFieldARAMA.getText();
    String kayit = "";
    String tur, eng;
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        kayit = okuyucu.nextLine();
        System.out.println("kayıt : " + kayit);
        if(this.jRadioButtonTUMU.isSelected()) {
          tur = kayit.substring(0, kayit.indexOf("=")-1);
          System.out.println("Türkçe : " + tur);
          eng = kayit.substring(kayit.indexOf("=")+2, kayit.length());
          System.out.println("English : " + eng);
          if(arananKelime.equalsIgnoreCase(tur)) {
            sonuc += "Aranan : " + arananKelime + " = " + eng + "\n";
          } else if(arananKelime.equalsIgnoreCase(eng)) {
            sonuc += "Searched : " + arananKelime + " = " + tur + "\n";
          }
        } else {
          // içinde geçen karakterleri bulur
          if(kayit.contains(arananKelime)) {
            sonuc += arananKelime + " -> " + kayit + "\n";
          }
        }
      }
      if(sonuc.equals("")) sonuc = "Aranan Kelime Bulunamadı";
      this.jTextAreaARAMA.setText(sonuc);
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(this, "HATA:" + ex.toString());
    }
  }//GEN-LAST:event_jButtonARAMAActionPerformed

  private void jButtonGUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUNCELLEActionPerformed
    listeGuncelle();
  }//GEN-LAST:event_jButtonGUNCELLEActionPerformed

  private void listeGuncelle() {
    dlmLISTE.clear();
    this.jListSIL.setModel(dlmLISTE);
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        this.dlmLISTE.addElement(okuyucu.nextLine());
      }
      this.jListSIL.setModel(dlmLISTE);
      okuyucu.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
  }
  
  private void jButtonSILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSILActionPerformed
    String adres = System.getProperty("user.dir") + "\\src\\sozluk.txt";
    String secilenKelime = this.jListSIL.getSelectedValue();
    System.out.println("Seçilen Kelime : " + secilenKelime);
    String kelimeler = "";    
    try {
      Scanner okuyucu = new Scanner(new File(adres));
      while(okuyucu.hasNext()) {
        String kayit = okuyucu.nextLine();
        if(!kayit.equals(secilenKelime)) {
          kelimeler += kayit + "\n";
        }
      }
      okuyucu.close();
    } catch (FileNotFoundException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
    System.out.println("Kelimeler : \n" + kelimeler);
    File dosya = new File(adres);
    try {
      FileWriter yazici = new FileWriter(dosya);
      BufferedWriter yaz = new BufferedWriter(yazici);
      yaz.write(kelimeler);
      //yaz.newLine();
      yaz.close();
      JOptionPane.showMessageDialog(this, "Silme Başarılı");
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(this, "HATA: " + ex.toString());
    }
    listeGuncelle();
  }//GEN-LAST:event_jButtonSILActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TurEngSozluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TurEngSozluk().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jButtonARAMA;
  private javax.swing.JButton jButtonGUNCELLE;
  private javax.swing.JButton jButtonKAYDET;
  private javax.swing.JButton jButtonLISTE;
  private javax.swing.JButton jButtonLISTELE;
  private javax.swing.JButton jButtonSIL;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JList<String> jListKELIMELER;
  private javax.swing.JList<String> jListSIL;
  private javax.swing.JPanel jPanelARAMA;
  private javax.swing.JPanel jPanelKAYDET;
  private javax.swing.JPanel jPanelLISTE;
  private javax.swing.JPanel jPanelLISTELE;
  private javax.swing.JPanel jPanelSILME;
  private javax.swing.JRadioButton jRadioButtonICINDE;
  private javax.swing.JRadioButton jRadioButtonTUMU;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTabbedPane jTabbedPaneSOZLUK;
  private javax.swing.JTextArea jTextAreaARAMA;
  private javax.swing.JTextArea jTextAreaLISTE;
  private javax.swing.JTextField jTextFieldARAMA;
  private javax.swing.JTextField jTextFieldENGLISH;
  private javax.swing.JTextField jTextFieldTURKCE;
  // End of variables declaration//GEN-END:variables
}
